// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SquaresPage {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm formDefault;
		
		protected System.Web.UI.HtmlControls.HtmlInputText XCoord;
		
		protected System.Web.UI.HtmlControls.HtmlInputText YCoord;
		
		protected System.Web.UI.WebControls.Button btnAddPt;
		
		protected System.Web.UI.WebControls.Button btnClearList;
		
		protected System.Web.UI.HtmlControls.HtmlInputText toBeRemoved;
		
		protected System.Web.UI.WebControls.Button btnRemovePts;
		
		protected System.Web.UI.WebControls.Button btnImportList;
		
		protected System.Web.UI.WebControls.Button btnExportList;
		
		protected System.Web.UI.WebControls.Button btnDeleteList;
		
		protected System.Web.UI.WebControls.Button btnCountSq;
		
		protected System.Web.UI.WebControls.Label lblPPP;
		
		protected System.Web.UI.WebControls.DropDownList dropPages;
		
		protected System.Web.UI.WebControls.DropDownList dropSortBy;
		
		protected System.Web.UI.WebControls.Button btnLeft;
		
		protected System.Web.UI.WebControls.Label lblNofN;
		
		protected System.Web.UI.WebControls.Button btnRight;
		
		protected System.Web.UI.WebControls.Label listOfPoints;
		
		protected System.Web.UI.WebControls.Label listOfSquares;
	}
}
